dillo-browser/dillo

ChangeLog, dillorc, doc/user_help.html, src/prefs.c
The DuckDuckGo service that redirects the links from the search page is returning a broken page for non-javascript browsers. They have a meta refresh tag in the body, instead of in the head.
Adding the kd=-1 argument causes the DuckDuckGo search results to point directly to the target page avoiding the redirection.
Fixes: #8
=> Fix DuckDuckGo search links

ChangeLog, dillorc, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/uicmd.cc
When using the mouse wheel to scroll a page, the default scroll step was causing a very slow scrolling speed. The new option "scroll_step" allows the user to define how many pixels the page is moved in every step of the mouse wheel. The default is increased to 100 pixels per step.
Here is an example where a [large page](https://html.spec.whatwg.org/#a-quick-introduction-to-html) is loaded in the original Dillo in the left and the version with the increased scroll step to 100 in the right. When using the mouse wheel the screen is moved much faster now:
[video.webm](https://github.com/dillo-browser/dillo/assets/3866127/592b7d1c-b62a-492f-80ab-6bf3ded3689d)
Fixes #22
=> Add scroll_step option

.github/workflows/build.yml, ChangeLog, README, doc/install.md, src/IO/tls_openssl.c
The function is not available in OpenSSL 1.1 with the `_get` suffix.
=> Add support for OpenSSL 1.1

.github/workflows/build.yml, ChangeLog, dw/textblock.cc, dw/widget.cc, test/html/Makefile.am, test/html/manual/max-width-body.html, test/html/manual/max-width-div.html, test/html/manual/max-width-html.html, test/html/manual/max-width-nested-div.html, test/html/render/max-width-body.html, test/html/render/max-width-body.ref.html, test/html/render/max-width-div.html, test/html/render/max-width-div.ref.html, test/html/render/max-width-html.html, test/html/render/max-width-html.ref.html, test/html/render/max-width-nested-div.html, test/html/render/max-width-nested-div.ref.html, test/html/render/min-width-body.html, test/html/render/min-width-body.ref.html, test/html/render/min-width-div.html, test/html/render/min-width-div.ref.html, test/html/render/min-width-html.html, test/html/render/min-width-html.ref.html, test/html/render/min-width-nested-div.html, test/html/render/min-width-nested-div.ref.html
The calculation for the width was not taking into account the `min-width` and `max-width` attributes. Fixes #36.
https://github.com/dillo-browser/dillo/assets/3866127/5d5613f5-7023-4b92-b9a7-3e23d1a5ed00
I need to check that there is nothing else breaking, as there are no layout tests.
=> Fix min-width and max-width CSS attributes

src/IO/http.c, src/IO/tls_openssl.c
Attempting to shutdown an SSL conection in LibreSSL was causing an error to be queued in the error queue, which was triggering the `assert(!ERR_get_error())` for a new connection. In OpenSSL this error was not queue in the "main" error queue, but only recorded for that SSL connection. so it was not triggering the assert.
The fix simply closes the file descriptor *after* performing the free operation.
@badsectoracula could you test this PR and check that fixes the #51 issue?
Fixes #51
=> Free SSL connection before closing file descriptor

ChangeLog, dillorc, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/uicmd.cc
The default tab height of 16 pixels was causing some usability issues as the tabs are quite small in large monitors. The default size is increased to 20 pixels and the new option "ui_tab_height" allows the user to specify a different value.
=> Add ui_tab_height option

ChangeLog, src/IO/tls_openssl.c
We cannot rely on the return value and the errno, the function SSL_get_error() must be used to determine what happen and if we need to retry again. A wrapper function translates the SSL error into a proper errno value.
In the case a premature EOF is sent by the server, the error queue is emptied before the error is returned.
Fixes: https://github.com/dillo-browser/dillo/issues/79
=> Handle errors in SSL_read() and SSL_write()

ChangeLog, dpi/file.c, src/uicmd.cc
Allows paths like `file:~/` and `file:~/.dillo/dillorc` to be opened by Dillo by expanding the tilde character `~` to the value of the `$HOME` environment variable.
Fixes: https://github.com/dillo-browser/dillo/issues/81
=> Expand tilde to home directory in local URLs

ChangeLog, src/table.cc, test/html/Makefile.am, test/html/render/table-td-width-percent-img.html, test/html/render/table-td-width-percent-img.ref.html, test/html/render/table-td-width-percent.html, test/html/render/table-td-width-percent.ref.html
Fixes #84, #54 
Before:
After:
See the date in the top right corner being cut:
Which is now visible:
=> Ignore td relative width attribute

dpid/dpidc.c
The bzero() function is removed in POSIX.1-2008.
Fixes: https://github.com/dillo-browser/dillo/issues/91
=> Use memset() instead of bzero()

dw/widget.cc, test/html/Makefile.am
=> Fix hackernews test

dpi/file.c
Fixes: https://github.com/dillo-browser/dillo/issues/87
Reported-by: dogma
=> Free auxiliary string in File_normalize_path()

dpi/file.c
Other platforms don't use $HOME.
Reported-by: dogma
=> Use dGethomedir() to get the home directory

.github/workflows/build.yml, ChangeLog, doc/install.md, dpid/Makefile.am, dpid/dpid.c, dpid/dpid_common.h, dpid/dpidrc.in
Add a Windows build to the CI using Cygwin and add the build process in the documentation. A small fix is also needed to let the DPI daemon find the DPI plugins when they have the ".dpi.exe" extension.
=> Add windows CI

ChangeLog, src/html.cc, src/styleengine.cc, test/html/Makefile.am, test/html/render/main-style.html, test/html/render/main-style.ref.html
Fixes: https://github.com/dillo-browser/dillo/issues/109
This was also affecting some pages that depended on styles applied to the `main` tag.
=> Add support for the main HTML tag

dpi/bookmarks.c
Simplifies and increases the contrast of the Bookmark pages and menus. Tables are removed in favor of HTML5 elements. For styles we add a simple CSS style sheet, common for all pages.
Fixes: https://github.com/dillo-browser/dillo/issues/108
=> Improve readability of bookmarks

ChangeLog, src/menu.cc
The W3C validator is now protected under a CloudFlare JavaScript challenge. However, it can be bypassed by opening directly the link after the redirection. It doesn't work if an HTML 5 page is loaded, as that would redirect to the Nu validator which will attempt to run the challenge again.
So the current solution is to use the "legacy" W3C validator for HTML 4.01 or older documents and the W3C Nu validator for HTML 5 documents only. Users would need to choose which one to use manually (at least for now).
The WDG validator at https://www.htmlhelp.org/tools/validator/ is gone, the server reports "Server unable to read htaccess file, denying access to be safe", so it has been removed.
Fixes: https://github.com/dillo-browser/dillo/issues/113
=> Fix HTML validator menu

src/IO/tls_openssl.c
The function SSL_get_peer_certificate() is deprecated in 3.0.0, but still defined as a compatibility macro.
Fixes: https://github.com/dillo-browser/dillo/issues/118
=> Use SSL_get1_peer_certificate() in OpenSSL 3

dillorc, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/uicmd.cc
Adds the `scroll_switches_tabs_reverse` option in dillorc to allows reversing the direction of tab switching based on the movement of the mouse wheel.
Fixes: #122 
See: https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/thread/F2EF4NHF3CBMJ3XZII2TFIE6MSXEE5AD/
=> Control the direction of tab scrolling

doc/install.md
The libgif library is not needed as Dillo has a builtin GIF support.
Fixes: https://github.com/dillo-browser/dillo/issues/128
Reported-by: dogma
=> Remove libgif dependency from docs

dpi/downloads.cc
=> Use uppercase "Dillo" for the user agent

ChangeLog, dpi/file.c, src/cache.c
When a <meta> tag reports the "text/xhtml" content, we were correcting it to the type guessed in TypeDet. However, the current implementation to guess XHTML and HTML pages fails if the doctype is not at the start of the document, falling back to text/plain.
A more robust solution is to set the TypeNorm to "application/xhtml+xml", which can be handled by a_Mime_get_viewer() as an HTML-like document.
Fixes: https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/thread/7GJ4AAMFFPEHOIYEOH4NHVMSXMJDFYXG/
=> Improve quirk for text/xhtml content type

.github/workflows/build.yml, ChangeLog, dillorc, src/menu.cc, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/url.c
This pull request implements an option to force all http urls to be upgraded to https, similar to [HTTPS-Only Mode](https://support.mozilla.org/en-US/kb/https-only-prefs) in Firefox.
This is implemented by changing all http urls to https when they are created in a_Url_new.
A http_force_https preference is provided as well as a menu bar item to toggle this mode.
=> Implement force https mode.

doc/user_help.in.html
When using "git describe" the resulting length of the version is too long for the header. As we only need to store the version somewhere in the manual, we place it at the end of the first paragraph.
=> Move version to first paragraph of the manual

dw/layout.cc
It is always shown, even when messages are turned of by "show_msg=NO", as the preferences are not available to dw. For now we disable it permanently by using the _MSG() macro.
Reported-by: Kevin Koster <dillo@ombertech.com>
See: https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/message/PPNR5FTO3YFDVAQCM4SDNVAF22JEV22W/
=> Disable "Layout::resizeIdle calls" message

src/ui.cc
The old manual page is no longer needed as we have the latest manual rendered in the new website.
=> Update online manual URL

doc/install.md
On macOS, Homebrew will install OpenSSL to different locations depending on which architecture you're on (Intel or ARM). It also doesn't put the headers and library files in the default search path for `gcc`.
This added instruction in the `doc/install.md` aligns with a similar instruction for BSD and is architecture and OpenSSL version agnostic (because it just asks Homebrew to tell us what the prefix is).
`pkg-config` could easily work across platforms or the lookup could be configured to test for homebrew, but I didn't want to make a much bigger change to the autoconf script.
=> Update macOS install instructions

AUTHORS, ChangeLog, doc/Cookies.txt
This also prevent RPM linter warns, error.
=> Convert some old files from iso8859-1 to utf-8 encoding

doc/install.md
Dillo is now packaged (bottled) in Homebrew as seen here - 
https://github.com/Homebrew/homebrew-core/blob/master/Formula/d/dillo.rb
=> Update macOS dillo install instructions

.github/workflows/build.yml, ChangeLog, doc/install.md, src/IO/tls_mbedtls.c
In Mbed TLS 3.6.0 there is now support for TLSv1.3, but it requires special handling so for now we disable it.
See: https://gitlab.alpinelinux.org/alpine/aports/-/commit/4dc36afaa81a4d73758b29fa77981d07dbae0080.patch
Fixes: https://github.com/dillo-browser/dillo/issues/158
=> Disable TLSv1.3 in MbedTLS 3.6.0 for now

src/IO/tls_openssl.c
It would be nice if X509_ALGOR could be made opaque at some point. There is a somewhat clumsy accessor X509_ALGOR_get0() that allows obtaining the ASN1_OBJECT sitting inside an X509_ALGOR. Use this instead.
=> Avoid reaching into X509_ALGOR

ChangeLog, doc/install.md
Cygwin doesn't seem to support detached threads used by the threaded DNS resolver at the same time the dynamic OpenSSL library is used. As a workaround we suggest disabling the threaded DNS (will use the same thread) if building with OpenSSL on Cygwin.
Fixes: https://github.com/dillo-browser/dillo/issues/172
=> Add workaround for OpenSSL in Cygwin

.github/workflows/build.yml, ChangeLog, test/html/Makefile.am, test/html/driver.sh
This is a continuation of https://github.com/dillo-browser/dillo/pull/176 as I accidentally closed it while trying to add a commit to test the CI, and prevented me from updating it further.
Original comment by @Kangie:
> This will enable tests to be easily run by downstream distributions.
> 
> These files are not included in the 3.1.0 release tarball, resulting in errors like:
> 
> ```
> make[4]: Entering directory '/var/tmp/portage/www-client/dillo-3.1.0/work/dillo-3.1.0/test/html'
> make[4]: *** No rule to make target 'render/b-div.html', needed by 'render/b-div.html.log'.  Stop
> ```
> 
> When distributions try to package and test the software.
=> Ensure the release tarball can run HTML rendering tests

ChangeLog, src/IO/tls_openssl.c
It may be returned when the server closes the connection, see:
https://www.openssl.org/docs/manmaster/man3/SSL_get_error.html
We simply handle it as if there was no error and return zero bytes read.
Fixes: https://github.com/dillo-browser/dillo/issues/175
=> Handle SSL_ERROR_ZERO_RETURN in OpenSSL

ChangeLog, src/png.c
The libpng library may emit warnings when decoding a PNG image, which are non-fatal. So far we were handling them as errors and stopping the decoding process, which prevents Dillo from decoding some images. In particular, images that emit the warning:
> iCCP: known incorrect sRGB profile
Fixes: https://github.com/dillo-browser/dillo/issues/179
Authored-by: dogma
=> Handle PNG warnings as non-fatal

configure.ac, dw/ooffloatsmgr.cc
Fixes: https://bugs.gentoo.org/933361
CC @asarubbo @Kangie 
**Note:** The `--enable-rtfl` flag will cause *a lot* of printf lines which are used to debug the rendering engine (with another tool called RTFL). They are not recommended while browsing as a user as they will slowdown the browser a lot.
=> Remove undefined floatRef debug line in RTFL

src/css.hh, src/html.cc, src/html.hh
The Tags array can be modified without changing the "ntags" number in the CSS side. To prevent errors, an static assert ensures the same number is used in both sides, which is known at compilation time.
Fixes: https://github.com/dillo-browser/dillo/issues/184
=> Ensure the same number of tags for CSS and HTML

ChangeLog, configure.ac
Closes milestone [3.1.1](https://github.com/dillo-browser/dillo/milestone/2)
=> Release version 3.1.1

ChangeLog, dillorc, doc/user_help.in.html, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/uicmd.cc, src/url.c
Adds support to load a custom page when a new tab is opened. The current behavior is set as the default, load a blank page. The location bar is only selected when the new tab page is the blank page, otherwise the page loaded gets the focus.
Fixes: https://github.com/dillo-browser/dillo/issues/124
=> Add new_tab_page option

src/html.cc, src/url.c
They are used for href="" in links or action="" in forms.
Fixes: https://github.com/dillo-browser/dillo/issues/190
=> Allow empty URLs with base URL set

ChangeLog, src/html.cc, test/html/manual/title-dup.html, test/html/manual/title-empty.html, test/html/manual/title-missing.html
When a page has an empty title like <title></title>, don't use it to set the tab label, but instead rely on the default tab label, which is computed from the file name.
=> Ignore empty page title for tab labels

ChangeLog, dpi/downloads.cc
The destructor was using a harcoded index to the elements to free from the original array of arguments used to call the wget program. When the user agent was introduced, the index of the elements that require free() shifted, causing the free() call to operate on the constant string of the user agent instead.
Rather than relying on the hardcoded index, two new pointers hold the values of the strings that need to be free()'d in the destructor. Further additions in the argument array won't cause more problems.
Reported-by: pastebin
Fixes: https://github.com/dillo-browser/dillo/issues/196
See: https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/message/IPWQYKTYTO5G2BH3UU5224FRUFWCVGSO/
=> Fix segfault in Done button of downloads

ChangeLog, src/html.cc, test/html/Makefile.am, test/html/render/meta-refresh-0-no-url.html, test/html/render/meta-refresh-0-no-url.ref.html
The content="0" attribute was wrongly parsed as the URL "0". The change makes the parser ignore a redirect with a content value that doesn't have ";" or "url=" after the delay number.
Fixes: https://github.com/dillo-browser/dillo/issues/204
=> Ignore meta refresh content without URL

.github/workflows/build.yml
For now we check gzip as it is widely available and has a medium compression ratio.
Fixes: https://github.com/dillo-browser/dillo/issues/208
=> Check release fits in a floppy disk of 1.44 MB

.github/workflows/build.yml
The useful space to store files inside a floppy is less than the capacity of the floppy itself:
```
% mkfs.msdos -C floppy.img 1440
mkfs.fat 4.2 (2021-01-31)
% stat -c %s floppy.img
1474560
% mkdir floppy
% sudo mount -o loop,uid=$USER floppy.img floppy
% dd if=/dev/zero bs=1 count=100M of=floppy/test
dd: error writing 'floppy/test': No space left on device
1457665+0 records in
1457664+0 records out
1457664 bytes (1,5 MB, 1,4 MiB) copied, 0,912079 s, 1,6 MB/s
% echo $((1474560 - 1457664))
16896
```
It needs a bit more than 16K to store the FAT table, so round it to 32K to allow some clearance for changes in FAT header size.
```
% echo $((1474560 - 32*1024))
1441792
```
=> Reduce floppy disk size after formatting

lout/container.hh
With the adreess sanitizer enabled there was an error:
>  AddressSanitizer: new-delete-type-mismatch
Caused by a size mismatch in the delete operator as the called destructor was the incorrect one.
=> Fix ASan new-delete-type-mismatch error

ChangeLog, src/IO/mime.c
Some website endpoints return information in JSON, which is helpful to be read as plain text in some situations.
An example is the following endpoint https://tls.browserleaks.com/tls, which provides TLS fingerprinting information in JSON, which will change when reloading the page (only when Dillo is linked with LibreSSL).
The original page https://tls.browserleaks.com/ uses JS and cannot be used in Dillo.
See: https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/message/6C5K4F6NBRUDSPNPWTXLQXCK3U3SI7DM/
=> Render JSON content as plain text

ChangeLog, dpi/vsource.c
Adds a line anchor so we can make hyperlinks to an specific line.
Additionally improves a bit the design of the line number colors:
Here is the old style:
And new:
=> Add anchor to HTML source lines and improve the design

ChangeLog, dw/layout.cc, dw/layout.hh, src/cssparser.cc, test/html/Makefile.am, test/html/render/github-infinite-loop.html, test/html/render/github-infinite-loop.ref.html
Workaround for #236, it stops the layout loop if we have reached 1000 iterations, so we don't enter an infinite loop and hoard the CPU forever. It also stops the layouting loop each 100 iterations to return the control to the FLTK event loop, so we keep the window responsive.
There is a bug in the layouting process involving floats and white-space wrapping that should be fixed. To debug it we will probably need the debug window merged first.
=> Workaround for infinite layout loop

doc/Makefile.am
Using $< in a non-suffix rule context is a GNUmake idiom
Reported-by: Alex <a1ex@dismail.de>
=> Stick to POSIX make rules

src/styleengine.cc
When a 1px value is used for the border, any zoom level that makes it
smaller makes the resulting size 0, so it disappears. Using round
instead leaves more room for zooming out before it disappears.
Fixes: https://github.com/dillo-browser/dillo/issues/240
=> Round CSS value after applying zoom level

ChangeLog, src/dialog.cc, src/form.cc
Prevents Dillo from checking if the boundary collides with the file by making the boundary have 70 random characters which have an extremely low probability of collision.
=> Avoid expensive boundary search inside file

ChangeLog, src/IO/tls_openssl.c
When a error causes the TLS connection to fail and stop, the conn struct is free on Tls_close_by_key(), so writing to conn->in_connect is not correct after that point. The solution is to only set the flag when the it is still valid.
Reported-by: Alex <a1ex@dismail.de>
Link: https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/thread/TY2JYCIPC7IQ32U6VC7ZOV3FVFFOE5K3/
=> Fix heap use after free in TLS conn on errors

dillorc
- Switch to HTTPS for Google search
- Fix Google search by adding gbv=1 param
- Avoid Google consent dialog by denying it
=> Fix Google search

ChangeLog, dw/fltkplatform.cc, dw/platform.hh, dw/style.hh, src/css.hh, src/cssparser.cc, src/html.cc, src/html_common.hh, src/styleengine.cc, src/styleengine.hh
Add support for more CSS units and changes the parser representation to a struct, so we don't need to eat more bits from the unit values.
Closes #48 and #174
=> Add support for more CSS units

ChangeLog, dillorc, doc/user_help.in.html, dw/fltkflatview.cc, dw/fltkflatview.hh, dw/fltkpreview.cc, dw/fltkpreview.hh, dw/fltkviewport.cc, dw/fltkviewport.hh, dw/layout.cc, dw/view.hh, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/uicmd.cc
Implements support for placing the vertical scrollbar on the left side by setting `scrollbar_on_left=YES` on dillorc. By default, continues to be on the right side.
See: https://www.toomanyatoms.com/software/mobilized_dillo.html
Authored-By: dogma
=> Add support for left scrollbar

ChangeLog, dillorc, doc/user_help.in.html, dw/fltkviewport.cc, dw/fltkviewport.hh, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/uicmd.cc
Adds support for scrolling full pages with the mouse wheel and clicking on the scrollbar.
=> Scroll page mode

ChangeLog, dillorc, dw/fltkviewport.cc, dw/fltkviewport.hh, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/uicmd.cc
Introduces the new option scroll_page_overlap to control the amount of pixels of overlap when scrolling to the next or previous page. Previously this value was taken from scroll_step, but now they are controlled independently.
Fixes: https://github.com/dillo-browser/dillo/issues/276
=> Control the page overlap independently

dw/fltkviewport.cc, dw/fltkviewport.hh, dw/types.hh
Repeat when holding the button over the scrollbar and jump to top and bottom when clicking on the scrollbar arrow buttons.
=> Page mode improvements

ChangeLog, dillorc, src/prefs.c
Set focus_new_tab=NO and show_quit_dialog=NO by default.
=> Flip focus_new_tab and show_quit_dialog

ChangeLog, src/IO/http.c
When performing a HTTPS request over a HTTP proxy, a direct connection is made to the remote server, so the GET line will be received as is. Therefore we shouldn't send the full URL but just the path.
Fixes: https://github.com/dillo-browser/dillo/issues/279
=> Only use full URL for HTTP proxies

src/styleengine.cc
Some images have the same background color as the page so they don't have a visible border. Always adding a border on images with a link breaks this property. Links continue to be discoverable by hovering with the mouse.
Fixes: https://github.com/dillo-browser/dillo/issues/270
=> Don't add border on images with a link

ChangeLog, src/dillo.cc, src/uicmd.cc, src/uicmd.hh
Fixes: https://github.com/dillo-browser/dillo/issues/255
Known limitations: External CSS and images are not fetched again, refetching them again causes issues.
=> Reload the current page on SIGUSR1 signal

test/html/driver.sh
This suppresses a warning on more modern systems while preserving the ability of older systems and CI/CD to run the test suite.
> WARNING: The convert command is deprecated in IMv7, \
> use "magick" instead of "convert" or "magick convert"
=> use `magick` instead of `convert` if available

dw/layout.cc, dw/layout.hh, dw/ui.cc
=> Reset resize counter when viewport changes size

ChangeLog, src/IO/tls.c, src/IO/tls.h, src/IO/tls_mbedtls.c, src/IO/tls_mbedtls.h, src/IO/tls_openssl.c, src/IO/tls_openssl.h, src/Makefile.am, src/dillo.cc, src/djpeg.h, src/dpng.h, src/jpeg.c, src/png.c, src/version.cc, src/version.hh
When reporting the version of Dillo with -v, print also the version of
the libraries it is currently using, as well as the features that were
enabled at build time. Notice the versions are reported by reading them
at runtime, so we can detect the version loaded at run time, regardless
of which version was used at link time.
All features are always printed, but prefixes with + if enabled or - if
disabled. This allows checking if the feature was disabled at configure
time or if it is missing in that version of Dillo.
=> Print version of libraries and features

.github/workflows/build.yml, ChangeLog, configure.ac, doc/dillo.1.in, doc/install.md, doc/user_help.in.html, src/IO/mime.c, src/IO/mime.h, src/Makefile.am, src/dicache.c, src/dwebp.h, src/jpeg.c, src/png.c, src/version.cc, src/webp.c
Adds WebP image support, enabled by default if libwebp is present at configure time.
Fixes: https://github.com/dillo-browser/dillo/issues/71
See: https://www.toomanyatoms.com/software/mobilized_dillo.html
=> Add WebP image support

.github/workflows/build.yml, doc/install.md
Homebrew has updated the default version of FLTK to 1.4, which is causing rendering issues in Dillo. So for now, we build with FLTK 1.3 by pinning it.
See: https://github.com/Homebrew/homebrew-core/pull/198029
See: https://github.com/dillo-browser/dillo/issues/246
=> Pin FLTK to 1.3 in homebrew

ChangeLog, dillorc, src/dicache.c, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/version.cc
Makes disabling certain formats posible without the need to rebuild Dillo from source.
See: https://github.com/dillo-browser/dillo/pull/312
=> Allow image formats to be disabled from dillorc

configure.ac, src/Makefile.am, src/version.cc
When git is available, records the git commit in the dillo binary, so dillo -v reports the version and the commit. Otherwise only the release version is reported (as we do now).
The commit is *always* recomputed when "make" is called. This allows switching branches, doing a dirty rebuild and still get the correct commit with "dillo -v".
Using AC_INIT() doesn't update the commit when the source is already configured.
Fixes: https://github.com/dillo-browser/dillo/issues/288
=> Add git commit to the reported version with -v

src/version.cc
The returned value from Fl::version() is a floating point number like 1.0303, not 10303, so we correct it to follow Fl::api_version().
=> Fix FLTK version for old releases

src/Makefile.am
Compare the commit used in the last rebuild to determine if it has changed, rather than using a phony target which always causes a rebuild.
=> Avoid rebuild when the git commit is the same

src/Makefile.am
Add the target commit.h as a dependency of version.o, so it gets
generated before being included in version.cc, otherwise when doing a
parallel build it can fail.
=> Fix build error for missing commit.h

ChangeLog, dillorc, src/Makefile.am, src/actions.c, src/actions.h, src/dillo.cc, src/html.cc, src/menu.cc, src/menu.hh, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/uicmd.cc, src/uicmd.hh
Allows the user to define additional entries in the link menu which will
execute the given program/script. Each actions is defined using the
"link_action" option. The link URL is stored in the $url enviroment
variable and the current page in $origin, so the user can customize how
do the handling.
Here is a simple example to add three new entries:
link_action="Debug variables:echo url=$url origin=$origin"
link_action="Open in MPV:mpv $url"
link_action="Open in Firefox:firefox $url"
The command is spawned in a forked process using the system() call,
which uses the shell to expand any variable. In particular, the $url
variable is set to the current URL being opened.
=> Add support for user actions in the link menu

ChangeLog, src/plain.cc
Line numbers can be referenced using the fragment L + line number. For
example, file://foo/bar.txt#L42 will cause Dillo to scroll to line 42.
Fixes: https://github.com/dillo-browser/dillo/issues/330
=> Support line fragments in plain text files

dpid/dpid.c, dpid/main.c, src/Makefile.am
On cases where the system directory cannot be opened, dpid will not load the builtin plugins causing Dillo to fail to work properly with file: or data: URLs. Reporting a failure to open the directory allows users to determine the cause of the problem.
See: https://github.com/dillo-browser/dillo/issues/337
=> Print error if dpi_dir cannot be opened

dw/layout.cc, test/html/manual/left-scrollbar.html
When the page is first layouted, we can then determine if the vertical scrollbar needs to be present. When the vertical scrollbar is on the left side, the whole content needs to be shifted to the right, so we need to allocate the top level widget again. The current fix simply marks the top level widget for allocation.
Fixes: https://github.com/dillo-browser/dillo/issues/359
=> Fix text under scrollbar on the left

.gitignore
The .deps folders are part of the build process and dirty git status. This ignores them in the project.
=> Add .deps/ to .gitignore

src/IO/mime.c
Allows inspecting their content before adding it to a feed reader by reading it as plain text.
=> Display RSS feeds as plain text

.github/workflows/build.yml, ChangeLog, configure.ac, doc/install.md, src/IO/http.c, src/Makefile.am, src/decode.c
Implements support for brotli (br) content encoding.
Fixes: https://github.com/dillo-browser/dillo/issues/377
=> Add brotli support

ChangeLog, doc/user_help.in.html, src/IO/about.c, src/cache.c, src/cache.h, src/dillo.cc, src/keys.cc, src/keys.hh
Fixes: https://github.com/dillo-browser/dillo/issues/66
=> Add about:keys to show keyboard shortcuts

ChangeLog, doc/user_help.in.html, src/html.cc
Small laptops and netbooks that lack a proper 3 button touchpad make it difficult to open a new tab. Using the control modifier makes is easier to open links in new tabs. It also allows mixing it with the shift modifier to control the focus.
=> Control + left click opens link in new tab

dillorc
See: https://github.com/dillo-browser/dillo/issues/338
=> Drop Google Search as it now requires JavaScript

lout/container.cc, lout/misc.cc
Avoid using assert as when building with NDEBUG defined they become a no-operation so the realloc is never done. Always perform the check and exit accordingly.
=> Don't use assert to check if realloc() failed

src/cache.c
A server may return the Content-Disposition in elements of a page like images, which would otherwise trigger several "save as" dialogs.
Fixes: https://github.com/dillo-browser/dillo/issues/398
CC: @campaul
=> Only parse Content-Disposition for root URLs

dw/fltkui.cc, src/ui.cc
The Emacs shortcut was overriding the FLTK behavior of selecting all input text.
Fixes: https://github.com/dillo-browser/dillo/issues/400
=> Make Ctrl+A select input text

test/html/driver.sh
The compare output command has now two numbers, so it will always fail if we compare it to "0".
```
++ compare -metric AE b-div.html_wdir/html.png b-div.html_wdir/ref.png b-div.html_wdir/diff.png
+ diffcount='0 (0)'
+ '[' '0 (0)' = 0 ']'
+ echo FAIL
FAIL
```
So we simply take the first one.
=> Fix newer compare output

dw/textblock_linebreaking.cc, test/html/Makefile.am, test/html/render/text-align-center.html, test/html/render/text-align-center.ref.html
Fix for #410 ~~and a prerequisite for finishing #403~~
Edit: this does have some interactions with #403 but turns out the fixes can be implemented independently.
There are two components to this change:
1) Only apply text alignment if the element being aligned is `inline` or `inline-block`.
2) Use the `alignStlye` from the container instead of from the element being aligned.
This PR also expands `test/text-align-center.html` with test cases for some other common scenarios
=> Fix text align

src/IO/dpi.c
When loading http://elpis.ws and then the issue 10, several images are requested via the data: URL which in turn causes many calls to the DPI datauri plugin, and it seems some may fail. When the DPI server fails to reply, an OpAbort is received by the CCC, but is ignored when it comes from the server side. This leaves the connection entry stale, and when navigating backwards, an attempt to read a free chunk of memory causes a crash.
Instead of ignoring the OpAbort, we handle it as if the CCC had received an OpEnd event, which propagates the received operation to the chain and then removes the connection.
=> Handle OpAbort from DPI CCC server side

ChangeLog, dlib/dlib.c, dlib/dlib.h, src/cache.c, src/dicache.c, src/dicache.h
These internal pages show the statistics on the current state of the network cache and decompressed image cache (dicache).
=> Add about:cache and about:dicache internal pages

src/cache.c
A copy of the buffer is done while injecting the content for about:cache and about:dicache, so the Dstr needs to be free'd after.
=> Fix internal page leak

.github/workflows/build.yml, lout/object.cc, lout/object.hh, src/dillo.cc, test/html/Makefile.am, test/html/driver.sh, test/html/leakfilter.awk, test/unit/containers.cc
=> Detect memory leaks in CI
