.github/workflows/build.yml, Makefile.am, README.md, doc/Makefile.am, lout/Makefile.am
Adds a CI and fixes some problems with the distcheck target.
=> Add CI with github actions

src/html.cc, src/table.cc, src/table.hh, test/table-thead-tfoot.html
See [Walley master](https://github.com/rodarima/dillo/pull/7)
=> Add preliminary support for thead, tbody and tfoot

.github/workflows/build.yml, doc/install.md
=> Add macOS 13 build in CI

.github/workflows/build.yml, configure.ac, doc/install.md, src/Makefile.am
=> Add FreeBSD to the CI

src/IO/tls_mbedtls.c, src/IO/tls_openssl.c
=> Report OpenSSL and mbedTLS versions

src/IO/tls_openssl.c
=> Fix TLS loop while in certificate dialog

ChangeLog, dillorc, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/uicmd.cc
Switches tabs when scrolling with the mouse wheel with the mouse over the tabs.
=> Allow mouse wheel to switch tabs

test/html/Makefile.am, test/html/render/margin-auto.html, test/html/render/margin-auto.ref.html
For now we just add the failing test, see #67.
=> Add margin auto HTML render test

test/html/Makefile.am, test/html/render/span-padding.html, test/html/render/span-padding.ref.html
Adds the failing test only, see #74.
=> Add span padding HTML render test

test/html/Makefile.am, test/html/render/div-100-percent-with-padding.html, test/html/render/div-100-percent-with-padding.ref.html, test/html/render/hackernews.html, test/html/render/hackernews.ref.html
Add a table test for Hacker News (#99) and another for content being draw out of the viewport.
=> Add Hacker News test

dw/textblock.cc, dw/widget.cc, test/html/Makefile.am, test/html/render/max-width-div-clamp.html, test/html/render/max-width-div-clamp.ref.html, test/html/render/min-width-div-extend.html, test/html/render/min-width-div-extend.ref.html, test/html/render/table-max-width.html, test/html/render/table-max-width.ref.html
=> Fix table with max-width and min-width

ChangeLog, doc/user_help.html
=> Improve help page

doc/user_help.html
Reported-by: dogma, monkeybusiness
=> Fix manual typos and clarify some parts

doc/install.md
=> Improve build docs

dpi/downloads.cc
Fixes: https://github.com/dillo-browser/dillo/issues/130
=> Use the current version in wget user agent

configure.ac
=> Release version 3.1.0-rc1

dillorc, doc/user_help.html
https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/message/5DGCSCREF2SMOADHBHJVCB33BMYDSBHG/
=> Fix scroll step docs

ChangeLog, src/table.cc, test/html/Makefile.am, test/html/render/table-missing-width-in-one-column.html, test/html/render/table-missing-width-in-one-column.ref.html
Fixes https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/message/H7JEBC2HYNJ6FUPQM7ILBP7I5FLU33IZ/
=> Fix table with relative width columns

ChangeLog
Fixes: https://github.com/dillo-browser/dillo/issues/160
=> Add release date for 3.1.0 in ChangeLog

.github/workflows/build.yml, src/html.cc
=> Add CI job to build with old C and C++ standards

ChangeLog, dillorc, doc/user_help.in.html, src/bw.c, src/bw.h, src/html.cc, src/keys.cc, src/keys.hh, src/keysrc, src/plain.cc, src/prefs.c, src/prefs.h, src/prefsparser.cc, src/styleengine.cc, src/styleengine.hh, src/ui.cc, src/uicmd.cc, src/uicmd.hh, src/web.cc
=> Add zoom control

doc/Makefile.am
This should fix [https://github.com/dillo-browser/dillo/issues/257](url)
=> Add doc/install.md to release

dpi/downloads.cc, src/capi.c
Send the user agent to the downloads DPI so we can use the same as Dillo uses from the http_user_agent option.
See: https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/thread/A6IHJ4TBGHJ3CT2UOMEAROSG2WRTRO6U/
=> Use Dillo user agent for downloads too

ChangeLog, configure.ac
Closes milestone https://github.com/dillo-browser/dillo/milestone/3
=> Release version 3.2.0

doc/user_help.in.html
=> Update the documentation for tab focusing behaviour

.github/workflows/build.yml
See: https://github.com/dillo-browser/dillo/actions/runs/14285249224/job/40039689315#step:3:136
=> Update package lists in CI

src/version.cc
=> Print brotli version with -v

test/html/Makefile.am, test/html/render/text-align-center.html, test/html/render/text-align-center.ref.html
=> Add test for text-align: center

ChangeLog, dillorc
See: https://en.wikipedia.org/wiki/Mojeek
=> Add mojeek search engine
